services:
  orchestrator:
    build:
      context: .
      dockerfile: Cmd/Orchestrator/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - calculator-network

  agent:
    build:
      context: .
      dockerfile: Cmd/Agent/Dockerfile
    environment:
      COMPUTING_POWER: 4
      TIME_ADDITION_MS: 100
      TIME_SUBTRACTION_MS: 100
      TIME_MULTIPLICATIONS_MS: 200
      TIME_DIVISIONS_MS: 200
      # GRPC_ADDR: "orchestrator:50051" # Нужно добавить в код агента
    depends_on:
      - orchestrator
    command: sh -c "sleep 5 && ./agent"
    networks:
      - calculator-network

networks:
  calculator-network:
    driver: bridge